# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-26 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0039_auto_20170906_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='discharge_disposition',
            field=models.CharField(choices=[('00', ' 00'), ('01', ' 01'), ('02', ' 02'), ('03', ' 03'), ('04', ' 04'), ('05', ' 05'), ('06', ' 06'), ('07', ' 07'), ('08', ' 08'), ('09', ' 09'), ('20', ' 20'), ('21', ' 21'), ('30', ' 30'), ('40', ' 40'), ('41', ' 41'), ('42', ' 42'), ('43', ' 43'), ('50', ' 50'), ('51', ' 51'), ('61', ' 61'), ('62', ' 62'), ('63', ' 63'), ('64', ' 64'), ('65', ' 65'), ('66', ' 66'), ('69', ' 69'), ('70', ' 70'), ('71', ' 71'), ('72', ' 72'), ('81', ' 81'), ('82', ' 82'), ('83', ' 83'), ('84', ' 84'), ('85', ' 85'), ('86', ' 86'), ('87', ' 87'), ('88', ' 88'), ('89', ' 89'), ('90', ' 90'), ('91', ' 91'), ('92', ' 92'), ('93', ' 93'), ('94', ' 94'), ('95', ' 95')], max_length=100, null=True),
        ),
    ]
