# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-12 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_curationuser_is_account_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='curationuser',
            name='require_mfa',
            field=models.BooleanField(default=True),
        ),
    ]
