# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-13 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_curationuser_require_mfa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationuser',
            name='mfa_type',
            field=models.CharField(choices=[('none', 'none'), ('sms', 'sms'), ('google', 'google')], default='google', max_length=20),
        ),
    ]
